services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6371:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - SERVICES=s3,sqs
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  db_data:
  db_config:
  cache:
  localstack_data:
